#ifndef CONFIG_H
#define CONFIG_H

//#define DEV_MODE

#define CONFIG_BUTTON_LENGTH 4
#define CONFIG_BUTTON_UP_ID 10
// PIN
#define CONFIG_BUTTON_UP_PIN 16
#define CONFIG_BUTTON_DOWN_ID 20
// PIN
#define CONFIG_BUTTON_DOWN_PIN 17
#define CONFIG_BUTTON_ENTER_ID 30
// PIN
#define CONFIG_BUTTON_ENTER_PIN 18
#define CONFIG_BUTTON_BACK_ID 40
// PIN
#define CONFIG_BUTTON_BACK_PIN 19
// PIN
#define CONFIG_SENSOR_220V_GRID_ALERT_PIN 27
// PIN
#define CONFIG_SENSOR_220V_INVERTER_ALERT_PIN 26
// PIN
#define CONFIG_LOAD_EXISTS_SENSOR_PIN 35
// PIN
#define CONFIG_POWER_SOURCE_SWITCH_PIN 23
// PIN
#define CONFIG_INVERTER_POWER_ON_PIN 25
// PIN
#define CONFIG_CHARGER_POWER_ON_PIN 32
// PIN
#define CONFIG_CHARGER_LOAD_EXISTS_PIN 34
// PIN
#define CONFIG_BUZZER_PIN 2


#define CONFIG_CONTEXT_LENGTH 9
#define CONFIG_CONTEXT_OBJ_DISPLAY 0
#define CONFIG_CONTEXT_OBJ_CHARGER 1
#define CONFIG_CONTEXT_OBJ_GRID 2
#define CONFIG_CONTEXT_OBJ_SETTINGS 3
#define CONFIG_CONTEXT_OBJ_POWER_SOURCE_SWITCH 4
#define CONFIG_CONTEXT_OBJ_CONTROL_CENTER 5
#define CONFIG_CONTEXT_OBJ_INVERTER 6
#define CONFIG_CONTEXT_OBJ_LOAD 7
#define CONFIG_CONTEXT_OBJ_BUZZER 8

#endif