#ifndef ACTIVITY_ID_H
#define ACTIVITY_ID_H

typedef enum {
	ACT_ID_NON = 0,
	ACT_ID_START,
	ACT_ID_MAIN,
	ACT_ID_SETTINGS,
	ACT_ID_SETTINGS_UPS_MODE,
	ACT_ID_SETTINGS_GRID_RETURN_DELAY,
	ACT_ID_SETTINGS_START_INVERTER_DELAY,
	ACT_ID_SETTINGS_ALARM_BATTERY_SOC,
	ACT_ID_SETTINGS_CRITICAL_BATTERY_SOC,
	ACT_ID_SETTINGS_START_CHARGING_SOC,
	ACT_ID_SETTINGS_STOP_CHARGING_SOC,
	ACT_ID_SETTINGS_SLEEP_TIMEOUT,
} activity_id_t;



#endif